### ISSUE TITLE
Software to-do List

### ISSUE THREAD

**Issue by YuhKuro** [YuhKuro/Numlocked#2]
## To-Do
- [ ] Implement pipes to C backend
- [ ] Implement C backend
- [ ] Update Firmware to handle inputs from software
## Bugs
- [ ] Fix Image Loading: The logo image path is still relative so we need to make sure its not dependent on where we execute main from.
Right now, the path to load image is still relative; fix to based on file structure.
